apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: dotnet 
  janus-idp.io/tekton: dotnet
  backstage.io/kubernetes-id: dotnet
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dotnet
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  