apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: dotnet
  janus-idp.io/tekton: dotnet
  backstage.io/kubernetes-id: dotnet
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dotnet
resources:
- deployment.yaml
- route.yaml
- service.yaml
